services:
  backend:
    image: 'tolnabert/solarwatch-backend:latest'
    # build:
    #   context: ./backend
    container_name: solarwatch-backend
    depends_on:
      - database
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}

  database:
#   don't use latest for prod, but rather use fix version
    image: 'postgres:16.3'
    container_name: solarwatch-database
    ports:
      - '5555:5432'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  frontend:
    image: 'tolnabert/solarwatch-frontend:latest'
    # build:
    #   context: ./frontend
    container_name: solarwatch-frontend
    depends_on:
      - backend
    ports:
      - '5008:5000'